### ISSUE TITLE
update command don't work

### ISSUE THREAD

**Issue by alvxi** [guipenedo/aero-discord-bot#8]
I deployed aero-discord-bot to heroku successfully, the bot is working (log print: Bot#code has connected to Discord!, no errors). When running `update` command there is no response from the bot, and due to the lack of docs, there isn't self-troubleshooting that I can do. Bot only reacts to the help command showing

```
No Category:
  help   Shows this message
  update 

Type ;help command for more info on a command.
You can also type ;help category for more info on a category.
```

**Comment by guipenedo** [comment]
Does the bot send a pm when someone joins the server for the first time?

**Comment by alvxi** [comment]
I just added a test user to the server and the message was sent via pm to that user, and fenix link works as expected. Now, the question is, there is any way to existent users (including the owner of the server) login into fenix via bot and associate their fenix account to the bot?

**Comment by guipenedo** [comment]
The link is sent to all users that do not have the role `ROLE_AUTH_NAME` every `NOTIFY_USER_INTERVAL` hours.
The !update command itself should sent the link if the user is not present in the database: https://github.com/guipenedo/aero-discord-bot/blob/master/src/run_bot.py#L42

**Comment by alvxi** [comment]
I have owner perms but I don't have the `ROLE_AUTH_NAME` (`autenticado`). I also set `NOTIFY_USER_INTERVAL` to 1 from the beginning and I didn't receive the bot pm yet. I understand your code, if there is an else exception the bot should pm everyone who launches the update command and it hasn't the `autenticado` role, but that isn't happening. I also tried to reorganize the order of the roles in the server, putting the role of the bot (all perms) on the top of the list, but it didn't solve the issue.

**Comment by guipenedo** [comment]
Are you sure there are no exceptions on the console? Perhaps you have disabled private messages from non friends and the bot can not message you? 
Either way you can generate the auth link manually:
`{FENIX_BASE_URL}/oauth/userdialog?client_id={1695915081466049}&redirect_uri={FENIX_REDIRECT_URI}/&state={Discord user id}`
You can get a user's discord id if you are in developer mode by right clicking them and selecting "copy id".
If you then go to the auth link for your own user id you should be able to authenticate and the bot will process you.
You can also try changing the NOTIFY_USER_INTERVAL to something like 0.017 (about 1 minute), I believe this parameter accepts floats though I am not entirely sure.

**Comment by alvxi** [comment]
I created a new discord server from scratch, added the bot to it and it's working flawlessly. Thanks for your help!
I also tried to define NOTIFY_USER_INTERVAL=0.017 as you suggested but logs showed an exception (not sure, but probably due to var only accepts int values).

PS: I don't know if it is already a functionality of the bot, but it would be very useful to have some type of calendar on a channel to let members know when an evaluation is coming in a pre-defined timeframe.

**Comment by guipenedo** [comment]
> PS: I don't know if it is already a functionality of the bot, but it would be very useful to have some type of calendar on a channel to let members know when an evaluation is coming in a pre-defined timeframe.

Yeah the bot is quite limited as it is, unfortunately I don't have a lot of free time and I also no longer study at IST so do not have as much motivation to add new features

**Comment by alvxi** [comment]
> Yeah the bot is quite limited as it is, unfortunately I don't have a lot of free time and I also no longer study at IST so do not have as much motivation to add new features

I fully understand, however, it's better than a simple RSS bot that retrieves only the manually configured RSS feeds. Who knows, if I have some free time in the future (which in IST isn't much probable, you may know) I may fork the repo and improve it. Thanks!
